config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :devices do
    resources :posts
  end

  get "/pages/:page" => "pages#show"

  root to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  # belongs_to :user, optional: true
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id', optional: true
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true
  has_many :posts

  def self.search(search)
    where("model ILIKE ? OR manufacturer ILIKE ? OR condition ILIKE ? OR title ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :device
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :selling, class_name: 'Device', foreign_key: 'seller_id'
  has_many :buying, class_name: 'Device', foreign_key: 'buyer_id'
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @devices = Device.all
    if params[:search]
      @devices = Device.search(params[:search]).order("created_at DESC")
    else
      @devices = Device.all.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @device = Device.new
  end

  def edit
  end

  def create
    @device = Device.new(device_params)
    @device.seller_id = current_user.id

    if @device.save
      redirect_to @device, notice: 'Device was successfully created.'
    else
      render :new
    end
  end

  def update
    if @device.update(device_params)
      redirect_to @device, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @device.sold? != true
      @device.destroy
    end

    redirect_to devices_url, notice: 'Location was successfully destroyed.'
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:model, :title, :manufacturer, :condition, :price, :zip_code, :sold?)
  end
end

app/controllers/pages_controller.rb
  class PagesController < ApplicationController
    def show
      @user = current_user
      @devices_sold = @user.selling
      @devices_bought = @user.buying
      render template: "pages/#{params[:page]}", locals: {}
    end
  end  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_device
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.device_id = @device.id
    @post.user_id = current_user.id

    if @post.save
      redirect_to device_posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(device_params)
      redirect_to @post, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @post.device.sold? != true
      @post.destroy
    end

    redirect_to posts_url, notice: 'Location was successfully destroyed.'
  end

  private

  def set_device
    @device = Device.find(params[:device_id])
  end

  def post_params
    params.require(:post).permit(:content, :device_id, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :first_name, :last_name, :zipcode, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :first_name, :last_name, :zipcode, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/_form.html.erb
<div>
  <%= form_for(@device, html: { class: 'form-horizontal' }) do |f| %>
    <% if @device.errors.any? %>
    <fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(location.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
          <% @device.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :model, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :model, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :manufacturer, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :manufacturer, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :title, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :title, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :condition, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :condition, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :price, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :price, class: 'form-control', required: true %>
        </div>
      </div>

      <div>
        <%= f.submit class: "btn btn-primary btn-lg"%>
      </div>
      <br/>
    <fieldset>
  <% end %>
  <%= link_to 'Back', devices_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/devices/_googlemap.html.erb
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=<%=Rails.application.secrets.google_api_key%>&q=<%=@device.seller.zipcode%>" allowfullscreen>Device Location
</iframe>

app/views/devices/edit.html.erb
<div class='page-header'>
  <h1>Edit Your Device</h1>
</div>

<%= render 'form', device: @device %>

app/views/devices/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Condition</th>
    </tr>
  </thead>
  
  <tbody>
    <% @devices.each do |device| %>
      <% if device.sold? == false %>
        <tr>
          <td><%= device.manufacturer %></td>
          <td><%= device.model %></td>
          <td><%= device.condition %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table> 

app/views/devices/new.html.erb
<div class='page-header'>
  <h1>Add a New Device</h1>
</div>
<% @device.seller_id = current_user.id %>
<%= render 'form', device: @device %>

app/views/devices/show.html.erb
<div class="jumbotron">
  <h1 class="display-3"><%=@device.manufacturer%>   |  <%=@device.model%></h1>
  <p class="lead"> <%="Price: $#{@device.price}"%></p>
  <p class="lead"> <%="Description: #{@device.title}"%></p>
  <hr class="my-4">

  <% if @device.seller == current_user %>
    <h3> <%=link_to 'Edit', edit_device_path(@device), class: "btn btn-primary btn-lg" %>  |  <%= link_to 'Destroy', @device, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-lg" %> </h3>
  <% end %>

  <%= render 'googlemap' %>

  <h3> <%=link_to 'Q & A for Device', device_posts_path(@device), class: "btn btn-primary btn-lg" %> </h3>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    Created By: <a href="https://github.com/itisjohnday">John Day</a>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="position:fixed, top:0">
  <a class="navbar-brand" href="/">Safe Swap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= new_device_path %>>Sell Your Device<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/devices">Phones</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Laptops</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tablets</a>
      </li>
      <% if current_user %>
        <li class="nav-item"> <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => "nav-link"%> </li>
        <li class="nav-item"> <a href="/pages/user_account" class="nav-link">Account</a></li>
      <% else %>
        <li class="nav-item"> <%= link_to 'Register', new_user_registration_path, :class => "nav-link"%> </li>
        <li class="nav-item"> <%= link_to 'Login',  new_user_session_path, :class => "nav-link"%> </li>
      <% end %> 
    </ul>
    <div class="navbar-nav mr-auto">
      <%= form_tag devices_path, :method => "get" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Devices", class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", :name => nil,  class: "btn btn-secondary my-2 my-sm-0"%>
      <% end %>
    </div>
  </div>
    

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Safeswap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="position:fixed top:0">
      <%= render 'layouts/header' %>
    </div>
    <div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>Welcome to Safe Swap!</h1>
  <h3>Concept:</h3>
  <p>A site that can provide a better alternative to Craigslist for selling your electronic devices.</p>
  <h3>Status:</h3>
  <p>Currently a project to apply learned web development.</p>
</div>

app/views/pages/user_account.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Condition</th>
      <th>Price</th>
    </tr>
  </thead>
  
  <tbody>
    <% @devices_bought.each do |device| %>
      <% if device.sold? == false %>
        <tr>You bought the following devices:</tr>
        
        <tr>
          <td><%= link_to device.manufacturer, device %></td>
          <td><%= link_to device.model, device %></td>
          <td><%= device.condition %></td>
          <td><%= "$#{device.price}" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>

  <tbody>
    <% @devices_sold.each do |device| %>
      <% if device.sold? == false %>
        <tr>You sold the following devices:</tr>
        <tr>
          <td><%= link_to device.manufacturer, device %></td>
          <td><%= link_to device.model, device %></td>
          <td><%= device.condition %></td>
          <td><%= "$#{device.price}" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table> 
<h3> <%=link_to 'Edit Account', edit_user_registration_path, class: "btn btn-primary btn-lg" %> </h3>

app/views/posts/_form.html.erb
<div class='well bs-component'>
  <%= form_for [@device, @post], class: 'form-horizontal' do |f| %>
    <% if @post.errors.any? %>
    <fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class='form-group'>
        <%= f.label :content, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :content, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="btn btn-primary btn-lg">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
  <%= link_to 'Back', device_posts_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/posts/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Poster</th>
      <th>Question</th>
    </tr>
  </thead>
  
  <tbody>
    <% @posts.each do |post| %>
        <tr>
          <td><%= post.user.username %></td>
          <td><%= post.content %></td>
        </tr>
    <% end %>
    
  </tbody>
</table> 
<h3> <%=link_to 'Add New Post', new_device_post_path, class: "btn btn-primary btn-lg" %> </h3>
<h3> <%=link_to 'Return to Device', device_path(@device.id), class: "btn btn-primary btn-lg" %> </h3>

app/views/posts/new.html.erb
<h2>Add New Question or Comment</h2>

<%= render 'form', post: @post %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>